Fix error in HUNIT_QUERY use due to table locking
Remove aliases from the HUNIT_QUERY to prevent an error message when
executing this query while all other tables are locked. I guess using
the aliases creates a new table, and MySQL complains at you if you run
a query on an unlocked table while other tables are locked. See SO post
here:
https://stackoverflow.com/questions/36467298/mysql-table-my-table-was-not-locked-with-lock-tables
And here's the error message:
mysql.connector.errors.DatabaseError: 1100 (HY000): Table 'comp_source' was not locked with LOCK TABLES